### ISSUE TITLE
counter not working with the last version 0.1.0

### ISSUE THREAD

**Issue by jerlfan** [PyMoDAQ/pymodaq_plugins_daqmx#2]
I am not able to use the counter with release 0.1.0. 
The 0D device is correctly initialized. When I choose "counter" as channel it is also fine. When I choose the counter there is the following error:

"Specified property is not supported by the device or is not applicable to the task.
Property: DAQmx_StartTrig_Type

Task Name: _unnamedTask<0>

Status Code: -200452
 in function DAQmxDisableStartTrig"

I am trying to fine the solution, but I may need help. For instance realease 0.0.4 works properly for the counter.

**Comment by seb5g** [comment]
It seems that the settings for the trigger are being applied onto the counter task (which doesn't make sense) so I think it is an issue in the code at the task initialisation where some cases (analog in/analog out/counter)are not properly written. Have a look there and let us know. If you're struggling I'll have a look.

**Comment by jerlfan** [comment]
Hello,

I tried to identify the problem. It seems that the task PyDAQmx.Task() when counter is chosen does not have the property DisableStartTrig(). I thus "pass" this part (line 537 daqmx.py):
**example code:**
 "if not trigger_settings.enable:
                if channel.source == 'Counter':
                    pass
                else:
                    err = self._task.DisableStartTrig()
                    if err != 0:
                        raise IOError(self.DAQmxGetErrorString(err))
            else:"

 and I can chose the counter Dev1/ctr0 without problem. 

However, when I start the grabbing, then another error appear:
"PyDAQmx.DAQmxFunctions.ExtSampClkSrcNotSpecifiedError: External sample clock source must be specified for this application.
Unspecified Property: DAQmx_SampClk_Src

Channel Name: Dev1/ctr0

Task Name: _unnamedTask<1>

Status Code: -200303
 in function DAQmxReadCounterU32Ex"

I continue my investigation but I think PyDAQmx counter task does not have attribute triger or Clk source.

**Comment by seb5g** [comment]
I think this is exactly the problem. What version of daqmx do you have by the way? I'm wondering if it could also be related to this...

**Comment by jerlfan** [comment]
What do you mean about version of daqmx? Do you mean the daqmx.py inside pymodaq_plugins_daqmx (V0.1.0) or the pyDAQmx version (v1.4.6)?

**Comment by seb5g** [comment]
no I mean the national instrument driver. the pydaqmx package is in fact a wrapper around the dll from NI. You can get the info from NI MAX i think.

**Comment by jerlfan** [comment]
OK. I have version 22.8.0f212 (2022 Q4).

**Comment by seb5g** [comment]
so it is fairly recent. So I think the issue is probably with my daqmx.py trying to apply things not meant for counters.

**Comment by jerlfan** [comment]
I will try to downgrade ni-daqmx to an older version to confirm this point. 
However, plugin daqmx.py in v0.0.4 of the pymodaq plugin is working fine. The difference is that no trigger was considered in this version.

**Comment by seb5g** [comment]
Well I tried to create a plugin including as much functionnalities. But indeed counters don't have such things. In fact when I now need to include daqmx features into my plugins I create some from scratch using the wrapper daqmx.py in hardware. You can find such examples into non-official packages that I use on very custom experiments:

https://github.com/PyMoDAQ/pymodaq_plugins_moke

https://github.com/PyMoDAQ/pymodaq_plugins_moke/blob/b0e19257cb422f55d77d3005b6d7eb1ea3ab0cda/src/pymodaq_plugins_moke/daq_viewer_plugins/plugins_1D/daq_1Dviewer_MokeMacro.py#L11

https://github.com/PyMoDAQ/pymodaq_plugins_moke/blob/b0e19257cb422f55d77d3005b6d7eb1ea3ab0cda/src/pymodaq_plugins_moke/daq_move_plugins/daq_move_Current.py#L25

https://github.com/PyMoDAQ/pymodaq_plugins_moke/blob/b0e19257cb422f55d77d3005b6d7eb1ea3ab0cda/src/pymodaq_plugins_moke/daq_move_plugins/daq_move_LedDC4104.py#L27

**Comment by seb5g** [comment]
Aurore Finco added functionnalities for counters in #3 should have a look if this solves the issues

**Comment by jerlfan** [comment]
Hello, 
I tried to use the update by Aurore Finco. I am still not able to use the counter properly (same error) with the daqmx detector. The daqmx_PLcounter is not suitable for me. Using the changes made by Aurore and her philosophy I could develop a Daqmx_simple_counter detector. What do you think?

**Comment by seb5g** [comment]
This is what I would advise!
